export default class MapActions {
    static GET_LOCATION = 'GET_LOCATION';
    static SEARCHED_LOCATION = 'SEARCHED_LOCATION';
    static NEARBY_REJ = 'NEARBY_REJ';
    static NEARBY_SUCCESS = 'NEARBY_SUCCESS';
    static NEARBY_DATA_REC = 'NEARBY_DATA_REC';
    static GET_LOCATION_SUCCESS = 'GET_LOCATION_SUCCESS';
    static SET_LOCATION = 'SET_LOCATION';
    static GET_LOCATION_REJ = 'GET_LOCATION_REJ';
    static SET_CURRENT_LOCATION = 'SET_CURRENT_LOCATION';
    static SET_DESTINATION = 'SET_DESTINATION';
    static GET_DIRECTION = 'GET_DIRECTION';
    static SUCCESS_DIRECTION = 'SUCCESS_DIRECTION';
    static ERROR_DIRECTION = 'ERROR_DIRECTION';
}